parameters: {}
environment: {}
packages:
    - name: proposals
      shared: false
      environment: {}
      parameters: {}
      annotations: {}
      functions:
        - name: register
          binary: false
          main: ""
          runtime: go:1.20
          web: true
          webSecure: false
          parameters: {}
          environment: {}
          annotations: {}
          limits: {}
